
// -------------------------------------------------------------------
// This file was automatically generated by the 'gulp manifest' task
// DO NOT directly edit it!
// -------------------------------------------------------------------

module.exports = {
    hook: [
		() => import('~/src/app/components/HomeScreen/reactium-hooks.js')
	],
};
